### ISSUE TITLE
Test cases to cover

### ISSUE THREAD

**Issue by blasrodri** [madrugada-labs/candidate-staking#7]
We need to cover **at least** the following test cases.

## Job
- ~~Authority is able to create "job A"~~
- ~~Authority is not able to create "job A" again~~
- ~~Someone that's not the authority tries to create a valid job, but fails since lacks permissions~~
- It's not possible to create a job that's not a uuid v4 (say for instance job_id = "hi job")

## Application
Several cases
1. user bob stakes an amount corresponding to tier 1 (recall formulas) on job_appilcation_id "123"
2. ~~(a) The job_application_id is chosen, so bob is paid rewarded accordingly~~
2. ~~(b) The job_application_id is **not** chosen, so bob is only given what he staked originally~~

Let's do the same exercise, but with bob staking on tier1, on tier1 and tier2, on tier1 + tier2 + tier 3 (all combinations)...
And we can add a case where there's bob and Alice staking in the same job application. And we ensure that each of them gets paid as they should.

## Some notes

From these test cases I realize that we'll need to have two things:
- ~~one is a state in which people cannot stake any more (so like a freeze)~~
- ~~once we are in this state, we need to be able to know how much money in total we'd need to pay in rewards. Because that's the extra that the **auhtority** will need to deposit to be able to cover for the reward. Once that amount is deposited, then we can remove the freeze state and let people redeem the right quantities.~~

I think this is a safer way of paying. We avoid having to lock too much money in the contract and exposing ourselves to a big hack. Plus, the only ones who should be able to redeem the amounts should be those who staked. No-one else.

**Comment by blasrodri** [comment]
Can we close this?

**Comment by dhruvja** [comment]
Lets merge the pull request, this issue would get close automatically
